
class ApplyModel {
  int _id;
  String _bizId;
  String _bizTitle;
  int _flowId;
  String _flowName;
  String _flowCode;
  SysModule _sysModule;
  String _currentBy;
  String _currentByName;
  int _createBy;
  String _createByName;
  String _bizKey;
  String _createDate;
  bool _draft;
  String _currentNodeName;
  String _finishDate;
  String _typeX;
  String _imgUrl;
  String _regionCode;
  String _regionName;

  Autogenerated(
      {int id,
        String bizId,
        String bizTitle,
        int flowId,
        String flowName,
        String flowCode,
        SysModule sysModule,
        String currentBy,
        String currentByName,
        int createBy,
        String createByName,
        String bizKey,
        String createDate,
        bool draft,
        String currentNodeName,
        String finishDate,
        String typeX,
        String imgUrl,
        String regionCode,
        String regionName}) {
    this._id = id;
    this._bizId = bizId;
    this._bizTitle = bizTitle;
    this._flowId = flowId;
    this._flowName = flowName;
    this._flowCode = flowCode;
    this._sysModule = sysModule;
    this._currentBy = currentBy;
    this._currentByName = currentByName;
    this._createBy = createBy;
    this._createByName = createByName;
    this._bizKey = bizKey;
    this._createDate = createDate;
    this._draft = draft;
    this._currentNodeName = currentNodeName;
    this._finishDate = finishDate;
    this._typeX = typeX;
    this._imgUrl = imgUrl;
    this._regionCode = regionCode;
    this._regionName = regionName;
  }

  int get id => _id;
  set id(int id) => _id = id;
  String get bizId => _bizId;
  set bizId(String bizId) => _bizId = bizId;
  String get bizTitle => _bizTitle;
  set bizTitle(String bizTitle) => _bizTitle = bizTitle;
  int get flowId => _flowId;
  set flowId(int flowId) => _flowId = flowId;
  String get flowName => _flowName;
  set flowName(String flowName) => _flowName = flowName;
  String get flowCode => _flowCode;
  set flowCode(String flowCode) => _flowCode = flowCode;
  SysModule get sysModule => _sysModule;
  set sysModule(SysModule sysModule) => _sysModule = sysModule;
  String get currentBy => _currentBy;
  set currentBy(String currentBy) => _currentBy = currentBy;
  String get currentByName => _currentByName;
  set currentByName(String currentByName) => _currentByName = currentByName;
  int get createBy => _createBy;
  set createBy(int createBy) => _createBy = createBy;
  String get createByName => _createByName;
  set createByName(String createByName) => _createByName = createByName;
  String get bizKey => _bizKey;
  set bizKey(String bizKey) => _bizKey = bizKey;
  String get createDate => _createDate;
  set createDate(String createDate) => _createDate = createDate;
  bool get draft => _draft;
  set draft(bool draft) => _draft = draft;
  String get currentNodeName => _currentNodeName;
  set currentNodeName(String currentNodeName) =>
      _currentNodeName = currentNodeName;
  String get finishDate => _finishDate;
  set finishDate(String finishDate) => _finishDate = finishDate;
  String get typeX => _typeX;
  set typeX(String typeX) => _typeX = typeX;
  String get imgUrl => _imgUrl;
  set imgUrl(String imgUrl) => _imgUrl = imgUrl;
  String get regionCode => _regionCode;
  set regionCode(String regionCode) => _regionCode = regionCode;
  String get regionName => _regionName;
  set regionName(String regionName) => _regionName = regionName;


  static List<ApplyModel>  fromListJson(List<dynamic> listJson){

    List<ApplyModel>  list = [];

    listJson?.forEach((json){
      list.add(ApplyModel.fromJson(json));
    });

    return list;
  }



  ApplyModel.fromJson(Map<String, dynamic> json) {
    _id = json['id'];
    _bizId = json['bizId'];
    _bizTitle = json['bizTitle'];
    _flowId = json['flowId'];
    _flowName = json['flowName'];
    _flowCode = json['flowCode'];
    _sysModule = json['sysModule'] != String
        ? new SysModule.fromJson(json['sysModule'])
        : String;
    _currentBy = json['currentBy'];
    _currentByName = json['currentByName'];
    _createBy = json['createBy'];
    _createByName = json['createByName'];
    _bizKey = json['bizKey'];
    _createDate = json['createDate'];
    _draft = json['draft'];
    _currentNodeName = json['currentNodeName'];
    _finishDate = json['finishDate'];
    _typeX = json['typeX'];
    _imgUrl = json['imgUrl'];
    _regionCode = json['regionCode'];
    _regionName = json['regionName'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this._id;
    data['bizId'] = this._bizId;
    data['bizTitle'] = this._bizTitle;
    data['flowId'] = this._flowId;
    data['flowName'] = this._flowName;
    data['flowCode'] = this._flowCode;
    if (this._sysModule != null) {
      data['sysModule'] = this._sysModule.toJson();
    }
    data['currentBy'] = this._currentBy;
    data['currentByName'] = this._currentByName;
    data['createBy'] = this._createBy;
    data['createByName'] = this._createByName;
    data['bizKey'] = this._bizKey;
    data['createDate'] = this._createDate;
    data['draft'] = this._draft;
    data['currentNodeName'] = this._currentNodeName;
    data['finishDate'] = this._finishDate;
    data['typeX'] = this._typeX;
    data['imgUrl'] = this._imgUrl;
    data['regionCode'] = this._regionCode;
    data['regionName'] = this._regionName;
    return data;
  }
}

class SysModule {
  String _text;
  String _value;

  SysModule({String text, String value}) {
    this._text = text;
    this._value = value;
  }

  String get text => _text;
  set text(String text) => _text = text;
  String get value => _value;
  set value(String value) => _value = value;

  SysModule.fromJson(Map<String, dynamic> json) {
    _text = json['text'];
    _value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['text'] = this._text;
    data['value'] = this._value;
    return data;
  }
}